### ISSUE TITLE
Support upstream proxies

### ISSUE THREAD

**Issue by eastebry** [stripe/smokescreen#131]
Hello! I'm not sure if this project is still maintained, or if this is a feature you are interested in supporting within Smokescreen.

I'd like to be able to configure smokescreen so that it forwards (allowed) requests to an upstream proxy. Go programs generally respect the `http_proxy`, `https_proxy`, `no_proxy` environment variables. Running smokescreen with this invocation almost works:
```
$ HTTP_PROXY=http://10.0.0.1:9999 HTTPS_PROXY=http://10.0.0.1:9999 ./smokescreen --allow-range 10.0.0.1/32
```
HTTP connections work, CONNECT requests will give this error:
```
 level":"error","msg":"Failed to connect to remote host: parse \"192.168.0.12:9999\": first path segment in URL cannot contain colon"
```

I've traced this error back to stripe/goproxy, and opened a PR: https://github.com/stripe/goproxy/pull/18. `CONNECT` requests should work after merging this PR.

Thanks! If upstream proxies is not a feature you want to support, no worries, I'll look elsewhere.

**Comment by mattm-stripe** [comment]
fixed in #132
